# © 2009 EduSense BV (<http://www.edusense.nl>)
# © 2011-2013 Therp BV (<https://therp.nl>)
# © 2016 Akretion (Alexis de Lattre - alexis.delattre@akretion.com)
# Copyright 2016-2022 Tecnativa - Pedro M. Baeza
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).

from odoo import _, api, fields, models
from odoo.exceptions import UserError, ValidationError


class AccountPaymentOrder(models.Model):
    _name = "account.payment.order"
    _description = "Payment Order"
    _inherit = ["mail.thread", "mail.activity.mixin"]
    _order = "id desc"
    _check_company_auto = True

    name = fields.Char(
        string="Reference", readonly=True, copy=False, default=lambda self: _("New")
    )
    payment_method_line_id = fields.Many2one(
        comodel_name="account.payment.method.line",
        required=True,
        ondelete="restrict",
        tracking=True,
        check_company=True,
        index=True,
        domain="[('payment_order_ok', '=', True), "
        "('payment_type', '=', payment_type), ('company_id', '=', company_id)]",
        string="Payment Mode",
    )
    payment_type = fields.Selection(
        selection=[("inbound", "Inbound"), ("outbound", "Outbound")],
        readonly=True,
        required=True,
    )
    payment_method_id = fields.Many2one(
        comodel_name="account.payment.method",
        related="payment_method_line_id.payment_method_id",
        store=True,
    )
    payment_method_code = fields.Char(
        related="payment_method_line_id.payment_method_id.code", store=True
    )
    company_id = fields.Many2one(
        "res.company",
        ondelete="cascade",
        required=True,
        index=True,
        default=lambda self: self.env.company,
    )
    company_currency_id = fields.Many2one(related="company_id.currency_id", store=True)
    bank_account_link = fields.Selection(
        related="payment_method_line_id.bank_account_link",
    )
    allowed_journal_ids = fields.Many2many(
        comodel_name="account.journal",
        compute="_compute_allowed_journal_ids",
        string="Allowed journals",
    )
    journal_id = fields.Many2one(
        comodel_name="account.journal",
        compute="_compute_journal_id",
        store=True,
        precompute=True,
        string="Bank Journal",
        ondelete="restrict",
        tracking=True,
        check_company=True,
        domain="[('id', 'in', allowed_journal_ids)]",
    )
    # The journal_id field is only required at confirm step, to
    # allow auto-creation of payment order from invoice
    company_partner_bank_id = fields.Many2one(
        related="journal_id.bank_account_id",
        string="Company Bank Account",
    )
    state = fields.Selection(
        selection=[
            ("draft", "Draft"),
            ("open", "Confirmed"),
            ("generated", "File Generated"),
            ("uploaded", "File Uploaded"),
            ("cancel", "Cancel"),
        ],
        string="Status",
        readonly=True,
        copy=False,
        default="draft",
        tracking=True,
        index=True,
    )
    date_prefered = fields.Selection(
        selection=[
            ("now", "Immediately"),
            ("due", "Due Date"),
            ("fixed", "Fixed Date"),
        ],
        compute="_compute_date_prefered",
        store=True,
        precompute=True,
        string="Payment Execution Date Type",
        required=True,
        tracking=True,
    )
    date_scheduled = fields.Date(
        string="Payment Execution Date",
        tracking=True,
        help="Select a requested date of execution if you selected 'Due Date' "
        "as the Payment Execution Date Type.",
    )
    date_generated = fields.Date(string="File Generation Date", readonly=True)
    date_uploaded = fields.Date(string="File Upload Date", readonly=True)
    generated_user_id = fields.Many2one(
        comodel_name="res.users",
        string="Generated by",
        readonly=True,
        ondelete="restrict",
        copy=False,
        check_company=True,
    )
    payment_line_ids = fields.One2many(
        comodel_name="account.payment.line",
        inverse_name="order_id",
        string="Transactions",
    )
    payment_ids = fields.One2many(
        comodel_name="account.payment",
        inverse_name="payment_order_id",
        string="Payment Transactions",
        readonly=True,
    )
    payment_count = fields.Integer(
        compute="_compute_payment_count",
        store=True,
        string="Number of Payment Transactions",
    )
    total_company_currency = fields.Monetary(
        compute="_compute_total", store=True, currency_field="company_currency_id"
    )
    move_ids = fields.One2many(
        comodel_name="account.move",
        inverse_name="payment_order_id",
        string="Journal Entries",
        readonly=True,
    )
    move_count = fields.Integer(
        compute="_compute_move_count", string="Number of Journal Entries"
    )
    description = fields.Char()
    payment_file_id = fields.Many2one("ir.attachment", string="Payment File Attachment")
    payment_file_datas = fields.Binary(
        related="payment_file_id.datas", string="Payment File"
    )
    payment_file_name = fields.Char(
        related="payment_file_id.name", string="Payment Filename"
    )

    _sql_constraints = [
        (
            "name_company_unique",
            "unique(name, company_id)",
            "A payment order with the same number already exists in this company.",
        )
    ]

    @api.depends("payment_method_line_id")
    def _compute_allowed_journal_ids(self):
        for record in self:
            allowed_journals = False
            if record.payment_method_line_id:
                allowed_journals = record.payment_method_line_id.journal_id
                if (
                    record.payment_method_line_id.bank_account_link == "variable"
                    and record.payment_method_line_id.alternative_journal_ids
                ):
                    allowed_journals |= (
                        record.payment_method_line_id.alternative_journal_ids
                    )
            record.allowed_journal_ids = allowed_journals

    def unlink(self):
        for order in self:
            if order.state == "uploaded":
                raise UserError(
                    _(
                        "You cannot delete an uploaded payment order. You can "
                        "cancel it in order to do so."
                    )
                )
            if order.payment_file_id:
                order.payment_file_id.unlink()
        return super().unlink()

    @api.constrains("payment_type", "payment_method_line_id")
    def _payment_order_constraints(self):
        for order in self:
            if (
                order.payment_method_line_id
                and order.payment_method_line_id.payment_type != order.payment_type
            ):
                payment_type2label = dict(
                    self.env["account.payment.method"].fields_get(
                        "payment_type", "selection"
                    )["payment_type"]["selection"]
                )
                raise ValidationError(
                    _(
                        "The payment type (%(ptype)s) is not the same as the payment "
                        "type of the payment mode (%(pmode)s)",
                        ptype=payment_type2label[order.payment_type],
                        pmode=payment_type2label[
                            order.payment_method_line_id.payment_type
                        ],
                    )
                )

    @api.constrains("date_scheduled")
    def _check_date_scheduled(self):
        today = fields.Date.context_today(self)
        for order in self:
            if order.date_scheduled:
                if order.date_scheduled < today:
                    raise ValidationError(
                        _(
                            "On payment order %(porder)s, the Payment Execution Date "
                            "is in the past (%(exedate)s).",
                            porder=order.name,
                            exedate=order.date_scheduled,
                        )
                    )

    @api.depends("payment_line_ids", "payment_line_ids.amount_company_currency")
    def _compute_total(self):
        # TODO read_group ?
        for rec in self:
            rec.total_company_currency = sum(
                rec.mapped("payment_line_ids.amount_company_currency") or [0.0]
            )

    @api.depends("payment_ids")
    def _compute_payment_count(self):
        rg_res = self.env["account.payment"]._read_group(
            [("payment_order_id", "in", self.ids)],
            groupby=["payment_order_id"],
            aggregates=["__count"],
        )
        mapped_data = {order.id: pay_count for (order, pay_count) in rg_res}
        for order in self:
            order.payment_count = mapped_data.get(order.id, 0)

    @api.depends("move_ids")
    def _compute_move_count(self):
        rg_res = self.env["account.move"]._read_group(
            [("payment_order_id", "in", self.ids)],
            groupby=["payment_order_id"],
            aggregates=["__count"],
        )
        mapped_data = {order.id: move_count for (order, move_count) in rg_res}
        for order in self:
            order.move_count = mapped_data.get(order.id, 0)

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if "company_id" in vals:
                self = self.with_company(vals["company_id"])
            payment_method_line = False
            if vals.get("payment_method_line_id"):
                payment_method_line = self.env["account.payment.method.line"].browse(
                    vals["payment_method_line_id"]
                )
            if vals.get("name", _("New")) == _("New"):
                if payment_method_line and payment_method_line.specific_sequence_id:
                    vals["name"] = payment_method_line.specific_sequence_id.next_by_id()
                else:
                    vals["name"] = self.env["ir.sequence"].next_by_code(
                        "account.payment.order"
                    ) or _("New")
        return super().create(vals_list)

    @api.depends("payment_method_line_id")
    def _compute_date_prefered(self):
        for order in self:
            if order.payment_method_line_id.default_date_prefered:
                order.date_prefered = order.payment_method_line_id.default_date_prefered
            else:
                order.date_prefered = "due"

    @api.depends("payment_method_line_id")
    def _compute_journal_id(self):
        for order in self:
            if order.payment_method_line_id.journal_id:
                order.journal_id = order.payment_method_line_id.journal_id
            else:
                order.journal_id = False

    def action_uploaded_cancel(self):
        self.action_cancel()

    def cancel2draft(self):
        self.write({"state": "draft"})

    def action_cancel(self):
        # Unreconcile and cancel payments
        self.payment_ids.action_draft()
        self.payment_ids.action_cancel()
        if self.payment_file_id:
            self.payment_file_id.unlink()
        self.write(
            {
                "state": "cancel",
                "date_generated": False,
                "generated_user_id": False,
            }
        )

    def draft2open(self):
        """
        Called when you click on the 'Confirm' button
        Set the 'date' on payment line depending on the 'date_prefered'
        setting of the payment.order
        Re-generate the account payments.
        """
        today = fields.Date.context_today(self)
        for order in self:
            if not order.journal_id:
                raise UserError(
                    _("Missing Bank Journal on payment order %s.") % order.name
                )
            if (
                order.payment_method_id.bank_account_required
                and not order.journal_id.bank_account_id
            ):
                raise UserError(
                    _("Missing bank account on bank journal '%s'.")
                    % order.journal_id.display_name
                )
            if not order.payment_line_ids:
                raise UserError(
                    _("There are no transactions on payment order %s.") % order.name
                )
            # Unreconcile, cancel and delete existing account payments
            order.payment_ids.action_draft()
            order.payment_ids.action_cancel()
            order.payment_ids.unlink()
            # Prepare account payments from the payment lines
            payline_err_text = []
            group_paylines = {}  # key = hashcode
            for payline in order.payment_line_ids:
                try:
                    payline.draft2open_payment_line_check()
                except UserError as e:
                    payline_err_text.append(e.args[0])
                # Compute requested payment date
                if order.date_prefered == "due":
                    requested_date = payline.ml_maturity_date or payline.date or today
                elif order.date_prefered == "fixed":
                    requested_date = order.date_scheduled or today
                else:
                    requested_date = today
                # No payment date in the past
                requested_date = max(today, requested_date)
                # inbound: check option no_debit_before_maturity
                if (
                    order.payment_type == "inbound"
                    and order.payment_method_line_id.no_debit_before_maturity
                    and payline.ml_maturity_date
                    and requested_date < payline.ml_maturity_date
                ):
                    payline_err_text.append(
                        _(
                            "The payment mode '%(pmode)s' has the option "
                            "'Disallow Debit Before Maturity Date'. The "
                            "payment line %(pline)s has a maturity date %(mdate)s "
                            "which is after the computed payment date %(pdate)s.",
                            pmode=order.payment_method_line_id.display_name,
                            pline=payline.name,
                            mdate=payline.ml_maturity_date,
                            pdate=requested_date,
                        )
                    )
                payline.date = requested_date
                # Group options
                hashcode = (
                    payline.payment_line_hashcode()
                    if order.payment_method_line_id.group_lines
                    else payline.id
                )
                if hashcode in group_paylines:
                    group_paylines[hashcode]["paylines"] += payline
                    group_paylines[hashcode]["total"] += payline.amount_currency
                else:
                    group_paylines[hashcode] = {
                        "paylines": payline,
                        "total": payline.amount_currency,
                    }
            # Raise errors that happened on the validation process
            if payline_err_text:
                raise UserError(
                    _("There's at least one validation error:\n")
                    + "\n".join(payline_err_text)
                )

            order.env.flush_all()

            # Create account payments
            payment_vals = []
            for paydict in list(group_paylines.values()):
                # Block if a bank payment line is <= 0
                if paydict["total"] <= 0:
                    raise UserError(
                        _(
                            "The amount for Partner '%(partner)s' is negative "
                            "or null (%(amount).2f) !",
                            partner=paydict["paylines"][0].partner_id.name,
                            amount=paydict["total"],
                        )
                    )
                payment_vals.append(paydict["paylines"]._prepare_account_payment_vals())
            self.env["account.payment"].create(payment_vals)
        self.write({"state": "open"})

    def generate_payment_file(self):
        """Returns (payment file as string, filename)"""
        self.ensure_one()
        if self.payment_method_id.code in ("manual", "test_manual"):
            return (False, False)
        else:
            raise UserError(
                _(
                    "No handler for this payment method. Maybe you haven't "
                    "installed the related Odoo module."
                )
            )

    def open2generated(self):
        self.ensure_one()
        action = {}
        payment_file_bytes, filename = self.generate_payment_file()
        vals = {
            "state": "generated",
            "generated_user_id": self._uid,
            "date_generated": fields.Date.context_today(self),
        }
        if payment_file_bytes and filename:
            attachment = self.env["ir.attachment"].create(
                {
                    "name": filename,
                    "raw": payment_file_bytes,
                }
            )
            vals["payment_file_id"] = attachment.id
            action = {
                "name": filename,
                "type": "ir.actions.act_url",
                "url": f"web/content/?model={self._name}&id={self.id}&"
                f"filename_field=payment_file_name&field=payment_file_datas&"
                f"download=true&filename={filename}",
                "target": "new",
                # target: "new" and NOT "self", otherwise you get the following bug:
                # after this action, all UserError won't show a pop-up to the user
                # but will only show a warning message in the logs until the web
                # page is reloaded
            }
        self.write(vals)
        return action

    def generated2uploaded(self):
        self.payment_ids.action_post()
        # Perform the reconciliation of payments and source journal items
        for payment in self.payment_ids:
            lines_to_rec = self.env["account.move.line"]
            for line in (
                payment.payment_line_ids.move_line_id + payment.move_id.line_ids
            ):
                if line.account_id.id == payment.destination_account_id.id:
                    lines_to_rec |= line
            lines_to_rec.reconcile()
        self.write(
            {"state": "uploaded", "date_uploaded": fields.Date.context_today(self)}
        )

    def action_move_journal_line(self):
        self.ensure_one()
        action = self.env["ir.actions.actions"]._for_xml_id(
            "account.action_move_journal_line"
        )
        if self.move_count == 1:
            action.update(
                {
                    "view_mode": "form,list,kanban",
                    "views": False,
                    "view_id": False,
                    "res_id": self.move_ids[0].id,
                }
            )
        else:
            action["domain"] = [("id", "in", self.move_ids.ids)]
        action["context"] = dict(self.env.context, search_default_misc_filter=0)
        return action
